apiVersion: io.datameshaccelerator/v1
kind: DataProductDomain
metadata:
  name: {{ dataproductdomainname }}
  namespace: data-product-experience-plane
spec:
  templateName: "domain-template"
  domainName: {{ dataproductdomainname }}
  title: {{ dataproductdomainnametitle }}
  description: {{ dataproductdomainnamedescription }}
  responsibleTeam:
    name: {{ responsibleteamname }}
    contact: {{ responsibleteamemail }}
