apiVersion: io.datameshaccelerator/v1
kind: DataProductDomain
metadata:
  name: {{ dataproductdomain }}
  namespace: data-product-experience-plane
spec:
  domainName: {{ dataproductdomain }}
  title: {{ dataproductdomaintitle }}
  description: {{ dataproductdomaindescription }}
  responsibleTeam:
    name: {{ responsibleteamname }}
    contact: {{ responsibleteamemail }}
